tap 'homebrew/core'
tap 'homebrew/services'
tap 'homebrew/science'
tap 'thoughtbot/formulae'
brew 'rcm'
brew 'autojump'
brew 'hub'
brew 'r'
brew 'antigen'
brew 'rcm'

tap 'caskroom/cask'
cask_args appdir: '/Applications'
cask 'iterm2'
cask 'google-chrome'
cask '1password'
cask 'rstudio'
