format = """\
    $directory\
    $git_branch\
    $aws\
    $cmd_duration\
    $battery\
    $time\
    $line_break\
    $character\
  """

[character]
success_symbol = "➜"
error_symbol = "✖"

[python]
pyenv_version_name = true
pyenv_prefix = "v"
