prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "nodejs",
    "ruby",
    "python",
    "golang",
    "nix_shell",
    "aws",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "character",
]

[character]
symbol = "%{$(iterm2_prompt_mark)%}➜"
error_symbol = "%{$(iterm2_prompt_mark)%}✖"

[python]
pyenv_version_name = true
pyenv_prefix = "v"
