#!/bin/bash

touch "$HOME"/.psqlrc.local

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa

reset -Q

SUBLIME_PREFS_PATH="$HOME/Library/Application Support/Sublime Text 3/Packages/User/"

if [ -e "$SUBLIME_PREFS_PATH/Preferences.sublime-settings" ]; then
  echo "Sublime Text 3 User config already exists"
else
  mkdir -p "$SUBLIME_PREFS_PATH"
  /bin/ln -shf "$HOME/.sublime" "$SUBLIME_PREFS_PATH"
fi
