#!/bin/sh

touch "$HOME"/.psqlrc.local

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

reset -Q

antibody bundle < ~/.zsh_plugins > ~/.zsh_plugins.sh

SUBLIME_CONFIG_PATH="$HOME/Library/Application Support/Sublime Text 3/Packages"
SUBLIME_PKG_CTRL_FILE="$SUBLIME_CONFIG_PATH/Installed Packages/Package Control.sublime-package"

mkdir -p "$SUBLIME_CONFIG_PATH"
/bin/ln -shf "$HOME/.sublime" "$SUBLIME_CONFIG_PATH/User"

mkdir -p "$SUBLIME_CONFIG_PATH/Installed Packages/"
if [ ! -f "$SUBLIME_PKG_CTRL_FILE" ]; then
  curl -o "$SUBLIME_PKG_CTRL_FILE" "https://sublime.wbond.net/Package Control.sublime-package"
fi

VSCODE_CONFIG_PATH="$HOME/Library/Application Support/Code/User"

mkdir -p "$VSCODE_CONFIG_PATH"
/bin/ln -shf "$HOME/.vscode.settings.json" "$VSCODE_CONFIG_PATH/settings.json"
