#!/bin/bash

touch "$HOME"/.psqlrc.local

if [ ! -e "$HOME"/.vim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vimrc.bundles +PlugInstall +PlugClean! +qa

reset -Q

if [ -e "$HOME/Library/Application Support/Sublime Text 3/Packages/User" ]; then
  echo "Sublime Text 3 User config already exists"
else
  /bin/ln -shf "$HOME/.sublime" "$HOME/Library/Application Support/Sublime Text 3/Packages/User"
fi
