#! /bin/bash

set -eo pipefail

if ! type brew 2>/dev/null ; then
  echo 'Installing brew'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$(/opt/homebrew/bin/brew shellenv)"

brew update
brew bundle --global --file=./Brewfile

env RCRC=$HOME/src/dotfiles/rcrc rcup

if ! grep -q "/opt/homebrew/bin/zsh" /etc/shells ; then
  echo "Adding zsh to list of allowed shells"
  sudo sh -c 'echo /opt/homebrew/bin/zsh >> /etc/shells'
fi

chsh -s /opt/homebrew/bin/zsh
